#!/usr/bin/env python
"""
Format the varnishstat JSON output as CSV.

This file is in the public domain.

Author: Lasse Karstensen <lkarsten@varnish-software.com>, August 2015.
"""
import sys
import json
from pprint import pprint

def jsonchunksplit(fp):
    lines = []
    while True:
        buf = fp.readline()
        if buf == "":
            if len(lines) > 0:
                yield "\n".join(lines)
            break
        elif buf == "\n":
            continue
        elif buf == "}\n":
            lines += [buf]
            yield "\n".join(lines)
            lines = []
        else:
            lines += [buf[:-1]]


def main():
    first = True
    fp = open(sys.argv[1])

    for chunk in jsonchunksplit(fp):
        sample = json.loads(chunk)

        if first:
            first = False
            keys = []
            for k in sample.keys():
                if k == "timestamp":
                    continue
                if k.startswith("VBE."):
                    continue
                if k.endswith(".happy"):
                    continue
                if not k.startswith("SMA"): continue
                keys.append(k)

            keys.sort()
            keys.insert(0, "timestamp")
            print ",".join(keys)

        for j, key in enumerate(keys):
            if j > 0:
                sys.stdout.write(",")
            if key == "timestamp":
                sys.stdout.write(sample[key])
            else:
                sys.stdout.write("%s" % sample[key]["value"])
        sys.stdout.write("\n")

        if 0:
            keyname = keyname.replace(".", "__")
            s = ["INSERT %s,hostname=%s " % (keyname, os.uname()[1])]
            assert "value" in v
            s += ["value=%i" % v["value"]]
            final = "".join(s)

if __name__ == "__main__":
    main()
