#!/usr/bin/env python
# .- coding: utf-8 -.
"""
Collect and store varnishstat counters every n seconds for a time period.

This file is in the public domain.

Author: Lasse Karstensen <lkarsten@varnish-software.com>, August 2015.
"""
import sys
import subprocess
import argparse
from logging import basicConfig, INFO, DEBUG, info, error
from datetime import datetime, timedelta
from time import sleep
from pprint import pprint


def collect(outputfp, all_counters=False):
    "Run varnishstat from PATH and send output to outputfp."
    cmd = ["varnishstat", "-1", "-j"]

    if not all_counters:
        for i in ["MAIN", "MGT", "SMA", "VBE"]:
            cmd += ["-f", i]

    try:
        proc = subprocess.check_output(cmd, stderr=subprocess.PIPE)
    except subprocess.CalledProcessError as e:
        error("Error calling varnishstat: %s" % str(e))
        sleep(5)
        return
    outputfp.write(proc)

    if 0:
        import json
        data = json.loads(proc)
        pprint(data)


def main():
    parser = argparse.ArgumentParser(
        description="%s - Varnish runtime counter collector" % sys.argv[0],
        epilog="Tool to get continous collections of Varnish Cache counters.")
    parser.add_argument("interval",
                        help="Seconds to sleep between samples. (default: 5s)",
                        metavar="seconds", type=int, default=5)
    parser.add_argument("count",
                        help="Stop collection after this samples."
                        "(default 10)",
                        metavar="samples", type=int, default=10)

    parser.add_argument("-a", "--all-counters", action="store_true",
                        help="Collect all counters, including locks "
                        "and memory pools. (default: false)")
    parser.add_argument("--no-progress", help="Disable progress indicator.",
                        action="store_true")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="Verbose output.")
    parser.add_argument("--outputfile",
                        help="Target file to write output to.")

    if len(sys.argv) == 1:
        parser.print_help()
        exit()
    args = parser.parse_args()

    if args.verbose:
        basicConfig(level=DEBUG)
    else:
        basicConfig(level=INFO)

    i = 0
    try:
        if args.outputfile is not None:
            fp = open(args.outputfile, "a")
        else:
            fp = sys.stdout

        for i in range(0, args.count):
            collect(fp, all_counters=args.all_counters)
            sleep(args.interval)
        fp.close()
        info("\nCompleted collection after %i samples. Output written to %s.",
             args.count, args.outputfile)
    except KeyboardInterrupt:
        info("\nManual abort after %i samples. Output written to %s.",
             (i, args.outputfile))


if __name__ == "__main__":
    main()
